version: "3.8"

services:
  proxy:
    build: ./proxy
    # Prevent docker from self-daemonizing at runtime, and stay in the
    # foreground; otherwise, the container will stop immediately after
    # starting.
    entrypoint: ["nginx", "-g", "daemon off;"]
    expose:
      - 80
    ports:
      - "80:80"

  api:
    build: ./api
    expose:
      - 80

  frontend:
    expose:
      - 80
