# This contains override configurations on top of docker-compose.yml.
# By default this is always read by docker-compose everytime "up" is called.
version: "3.8"

# For convenience, this should only contain "prod" configurations, so we can
# isolate them as the default configurations every time we run "up".
# As for "dev" configurations, see "docker-compose.dev.yml"
#
# To ensure that the latest images are activated, execute a pull command:
# $ docker-compose pull
# $ docker-compose up
services:
  proxy:
    image: deojonathan/scaffold:proxy-latest

  api:
    image: deojonathan/scaffold:api-latest
    command: gunicorn --bind 0.0.0.0:80 -w 4 app:app

  frontend:
    image: deojonathan/scaffold:frontend-latest
    # Prevent docker from self-daemonizing at runtime, and stay in the
    # foreground; otherwise, the container will stop immediately after
    # starting.
    entrypoint: ["nginx", "-g", "daemon off;"]
